### ISSUE TITLE
[BUG] Ticket creation error

### ISSUE THREAD

**Issue by OverStyleFR** [ralphkb/sentinel-tickets#10]
**Describe the bug**
A error when i create a ticket with a fresh install of the bot.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Download the latest version of the bot.
2. Edit config fiiles
3. Start the bot and create a panel.
4. Create a ticket with click on the button and see the error on the console

**Screenshots**
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/8836480c-67ef-4267-8e50-5b14fdbd5d86)
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/dee00a86-5bf7-4af7-b8e4-0c952598d90e)

**Logs**
```bash
Error creating ticket: TypeError [InvalidType]: Supplied parameter is not a User nor a Role.
    at PermissionOverwrites.resolve (/home/container/node_modules/discord.js/src/structures/PermissionOverwrites.js:184:28)
    at /home/container/node_modules/discord.js/src/managers/GuildChannelManager.js:169:89
    at Array.map (<anonymous>)
    at GuildChannelManager.create (/home/container/node_modules/discord.js/src/managers/GuildChannelManager.js:169:51)
    at /home/container/events/interactionCreate.js:1440:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'InvalidType'
}
Error creating ticket: TypeError [InvalidType]: Supplied parameter is not a User nor a Role.
    at PermissionOverwrites.resolve (/home/container/node_modules/discord.js/src/structures/PermissionOverwrites.js:184:28)
    at /home/container/node_modules/discord.js/src/managers/GuildChannelManager.js:169:89
    at Array.map (<anonymous>)
    at GuildChannelManager.create (/home/container/node_modules/discord.js/src/managers/GuildChannelManager.js:169:51)
    at /home/container/events/interactionCreate.js:1440:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'InvalidType'
}
Error creating ticket: TypeError [InvalidType]: Supplied parameter is not a User nor a Role.
    at PermissionOverwrites.resolve (/home/container/node_modules/discord.js/src/structures/PermissionOverwrites.js:184:28)
    at /home/container/node_modules/discord.js/src/managers/GuildChannelManager.js:169:89
    at Array.map (<anonymous>)
    at GuildChannelManager.create (/home/container/node_modules/discord.js/src/managers/GuildChannelManager.js:169:51)
    at /home/container/events/interactionCreate.js:1440:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'InvalidType'
}
```

**Additional context**
I use the commit `e529cdd470b2713986ebb00e1827563899220874` and this bug is a suit of the #9 .

**Comment by OverStyleFR** [comment]
My bad i just realise that i have no change the default ID of "Supported rôle".

**Comment by OverStyleFR** [comment]
But a new error appear :
```bash
Error creating ticket: TypeError: Cannot read properties of undefined (reading 'send')
    at /home/container/events/interactionCreate.js:1567:38
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/container/events/interactionCreate.js:1492:17
    at async /home/container/events/interactionCreate.js:1439:13

```

Sreenshots : 

![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/671b2eaf-d2c1-400e-b646-a20d1c1903ea)
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/e05df9d3-ba72-4e40-a86d-737093eda8fb)
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/dbfaf7f9-a21e-4417-b5fc-38c8e2967702)

**Comment by OverStyleFR** [comment]
He can't delete the ticket.

Screenshot : 

![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/dc9f7b4a-ffbd-49a5-952e-fe6dd9eb2773)

Logs :
```bash
TypeError: Cannot read properties of undefined (reading 'send')
    at Object.execute (/home/container/events/interactionCreate.js:978:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'send')
    at Object.execute (/home/container/events/interactionCreate.js:978:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'send')
    at Object.execute (/home/container/events/interactionCreate.js:978:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ralphkb** [comment]
Hey, please make sure to keep your config up to date and to add at least the default log channel ID. This error means that the couldn't find the ID of the log channel for ticketCreate nor the default log channel ID.

All of the errors are basically related to the log channels in the config.

**Comment by OverStyleFR** [comment]
> Hey, please make sure to keep your config up to date and to add at least the default log channel ID. This error means that the bot couldn't find the ID of the log channel for ticketCreate nor the default log channel ID.
> 
> All of the errors are basically related to the log channels in the config. Following the changes I made in this commit back then. ([337935e](https://github.com/ralphkb/sentinel-tickets/commit/337935e8235f1aca92c72208aa0b78c997245985))

Okay yeah, my bad.
The config file hasn't updated, i miss the configuration of the logs.

Everything is clear now, but when i transcript the tickets with the command `/transcript` something show up on the console, nothing serrious but i want to know about it.
```bash
(node:26) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by ralphkb** [comment]
No worries, the config is always a reference and when you clone the repository you get it as config.yml.example so you can manually use it to update your own config.yml.
This warning can be ignored, no need to worry about it and it happens due to how the HTML transcripts are created by the NPM package the bot uses.
Thank you for using the bot, I will be closing the other issue since it is fixed and will keep this one open for some time in case you have further questions as well. 😄

**Comment by ralphkb** [comment]
Sure you can create a new issue as a feature request and I will see if it would be possible for me to add them or not.
I will also consider creating a discord server for the project, I'm still slowly focusing on making it more stable and evolving it while also learning new skills to keep improving it.
Once done in the future, I will probably add the discord server link to the README or my profile, will have to see.

**Comment by OverStyleFR** [comment]
> Sure you can create a new issue as a feature request and I will see if it would be possible for me to add them or not. I will also consider creating a discord server for the project, I'm still slowly focusing on making it more stable and evolving it while also learning new skills to keep improving it. Once done in the future, I will probably add the discord server link to the README or my profile, will have to see.

Okay, so no discord. Not even your personal discord?
