### ISSUE TITLE
[BUG] Used disallowed intents

### ISSUE THREAD

**Issue by OverStyleFR** [ralphkb/sentinel-tickets#12]
**Describe the bug**
When i start the bot on a new application bot and another discord server. (the last he's for dev, for testing)

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Download the latest commit.
2. Edit the config files.
3. Start the bot
4. See error on the console.

**Screenshots**
![image](https://github.com/ralphkb/sentinel-tickets/assets/94577363/bd0c8e5c-7c14-452c-bf39-c85358eda02f)

**Logs**
```bash
[Pterodactyl Daemon]: Finished pulling Docker container image
v18.19.1
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; /usr/local/bin/node /home/container/${JS_FILE}

up to date, audited 194 packages in 2s
34 packages are looking for funding
  run `npm fund` for details
4 low severity vulnerabilities
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
The slash command [add.js] has been loaded!
The slash command [alert.js] has been loaded!
The slash command [claim.js] has been loaded!
The slash command [close.js] has been loaded!
The slash command [delete.js] has been loaded!
The slash command [move.js] has been loaded!
The slash command [panel.js] has been loaded!
The slash command [pin.js] has been loaded!
The slash command [priority.js] has been loaded!
The slash command [remove.js] has been loaded!
The slash command [rename.js] has been loaded!
The slash command [reopen.js] has been loaded!
The slash command [slowmode.js] has been loaded!
The slash command [transcript.js] has been loaded!
The slash command [transfer.js] has been loaded!
The slash command [unclaim.js] has been loaded!
The slash command [blacklist.js] has been loaded!
The slash command [ping.js] has been loaded!
The slash command [reload.js] has been loaded!
The slash command [stats.js] has been loaded!
The slash command [unblacklist.js] has been loaded!
Error: Used disallowed intents
    at WebSocketShard.onClose (/home/container/node_modules/@discordjs/ws/dist/index.js:1132:18)
    at connection.onclose (/home/container/node_modules/@discordjs/ws/dist/index.js:676:17)
    at callListener (/home/container/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/home/container/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.emitClose (/home/container/node_modules/ws/lib/websocket.js:260:10)
    at TLSSocket.socketOnClose (/home/container/node_modules/ws/lib/websocket.js:1272:15)
    at TLSSocket.emit (node:events:529:35)
    at node:net:350:12
    at TCP.done (node:_tls_wrap:657:7)
container@pterodactyl~ Server marked as offline...
```

**Additional context**
Not same discord server has the other issue has been created.

**Comment by ralphkb** [comment]
You will have to open the discord developer portal and head over to the bot you created, then enable all the intents to make sure the bot will work properly.

**Comment by OverStyleFR** [comment]
> You will have to open the discord developer portal and head over to the bot you created, then enable all the intents to make sure the bot will work properly.

Ho Nice, Thanks you
![Screenshot_20240222_212617.jpg](https://github.com/ralphkb/sentinel-tickets/assets/94577363/4dc4b005-a0a9-443d-9e1c-b66616131e07)
