### ISSUE TITLE
Education

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#22]
How to add category?(add Butten)

**Comment by ralphkb** [comment]
Hello, if you want to add a new category you'll have to copy and paste one of the current categories in the config.yml (after you renamed the default config.yml.example) then paste it and increment the id by 1 while also changing the other values to fit your needs.
In the case of the default config, a 3rd category would have `id: 3` and the rest of the options are up to you to change.

Regarding the permission question from your other issue, if you want to change the permission for deleting a ticket you can do that in the slash commands settings in the config.
```YAML
  delete:
    enabled: true
    permission: "KickMembers"
```

By default the user can view their closed ticket but there's an option in case you want to remove the user upon ticket closure.
```YAML
closeRemoveUser: false # When enabled, the ticket creator will be removed from the ticket when it is closed and added back if the ticket is re-opened
```

This should hopefully answer both of your questions, I will be closing the other issue and please try to ask your questions within the same issue to avoid an unnecessary number of them. In case you have a feature request or bug report then you may report each one in it's own separate issue but please try to follow the templates for each respective case next time, thanks.

**Comment by MahdiTeaR** [comment]
![Screenshot 2024-04-02 100605](https://github.com/ralphkb/sentinel-tickets/assets/133818503/615218fd-17be-4058-8e15-eb78c9b888bd)
/home/runner/sentinel-tickets-3/node_modules/yaml/dist/public-api.js:73
            throw doc.errors[0];
            ^

YAMLParseError: A block sequence may not be used as an implicit map key at line 98, column 1:

        minLength: 10 # Set the minimum number of characters required for submi…

^

    at Composer.onError (/home/runner/sentinel-tickets-3/node_modules/yaml/dist/compose/composer.js:69:34)
    at Object.resolveBlockMap (/home/runner/sentinel-tickets-3/node_modules/yaml/dist/compose/resolve-block-map.js:32:21)
    at resolveCollection (/home/runner/sentinel-tickets-3/node_modules/yaml/dist/compose/compose-collection.js:13:27)
    at Object.composeCollection (/home/runner/sentinel-tickets-3/node_modules/yaml/dist/compose/compose-collection.js:47:16)
    at Object.composeNode (/home/runner/sentinel-tickets-3/node_modules/yaml/dist/compose/compose-node.js:31:38)
    at Object.composeDoc (/home/runner/sentinel-tickets-3/node_modules/yaml/dist/compose/compose-doc.js:33:23)
    at Composer.next (/home/runner/sentinel-tickets-3/node_modules/yaml/dist/compose/composer.js:149:40)
    at next (<anonymous>)
    at Composer.compose (/home/runner/sentinel-tickets-3/node_modules/yaml/dist/compose/composer.js:131:25)
    at compose.next (<anonymous>) {
  code: 'BLOCK_AS_IMPLICIT_KEY',
  pos: [ 8362, 8363 ],
  linePos: [ { line: 98, col: 1 }, { line: 99, col: 1 } ]
}

**Comment by MahdiTeaR** [comment]
Error add TicketCategories

**Comment by ralphkb** [comment]
It seems like you have issues with your configuration, try using this helpful website to find and fix them: https://www.yamllint.com/
