### ISSUE TITLE
Button "Delete"

### ISSUE THREAD

**Issue by iFaraons** [ralphkb/sentinel-tickets#42]
when I want to delete a ticket through the button, it is not deleted and there is an error. I would like to note that I have already connected the login to the channels.

This error comes when creating a ticket:
DiscordAPIError[10008]: Unknown Message
    at handleErrors (/root/sentinel-tickets/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/root/sentinel-tickets/node_modules/@discordjs/rest/dist/index.js:1120:23)
    at async SequentialHandler.queueRequest (/root/sentinel-tickets/node_modules/@discordjs/rest/dist/index.js:953:14)
    at async _REST.request (/root/sentinel-tickets/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async TextChannel.bulkDelete (/root/sentinel-tickets/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:290:9)
    at async Timeout._onTimeout (/root/sentinel-tickets/events/interactionCreate.js:2077:25) {
  requestBody: { files: undefined, json: undefined },
  rawError: { message: 'Unknown Message', code: 10008 },
  code: 10008,
  status: 404,
  method: 'DELETE',
  url: 'https://discord.com/api/v10/channels/1234584194127233084/messages/1234584204881170544'
}
This error comes when deleteing the ticket
TypeError: Cannot read properties of undefined (reading 'description')
    at /root/sentinel-tickets/node_modules/discord.js/src/structures/MessagePayload.js:190:25
    at Array.map (<anonymous>)
    at MessagePayload.resolveBody (/root/sentinel-tickets/node_modules/discord.js/src/structures/MessagePayload.js:188:45)
    at TextChannel.send (/root/sentinel-tickets/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:151:61)
    at Object.execute (/root/sentinel-tickets/events/interactionCreate.js:1070:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ralphkb** [comment]
Hey, please update the bot to the latest commit since it contains more fixes and make sure to double check your configuration. I can't seem to find issues with creation of tickets or deletion, so most likely your configuration has something or is missing something which is causing the error.

**Comment by iFaraons** [comment]
> Hey, please update the bot to the latest commit since it contains more fixes and make sure to double check your configuration. I can't seem to find issues with creation of tickets or deletion, so most likely your configuration has something or is missing something which is causing the error.

okey, thanks
