### ISSUE TITLE
Error Section blacklist role

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#56]
[Wednesday, May 15, 2024 at 7:28:49 PM UTC] [Bot v1.3.0] [NodeJS v20.11.1] [ERROR]
TypeError: Cannot read properties of undefined (reading 'slice')
    at parseDurationToMilliseconds (/home/runner/hrp-ticket/index.js:535:25)
    at Object.execute (/home/runner/hrp-ticket/events/interactionCreate.js:262:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ralphkb** [comment]
Hey, please write an explanation on how you got the first issue because the error is not enough and I can't seem to replicate it by testing.
For the creation of tickets issue, your bot either lacks permissions to see a category or you might have an outdated configuration where the categoryID and closedCategoryID were changed from a string to an array of strings. Checking those should fix the issue.
