### ISSUE TITLE
["ID"] correct format

### ISSUE THREAD

**Issue by LucasB25** [ralphkb/sentinel-tickets#60]
```
Error: categoryID and closedCategoryID of each configured ticket category must be an array, such as ["ID"]
    at findAvailableCategory (/home/pi/MusicBot/LucasB25/PanaisSupport/index.js:216:11)
    at Object.execute (/home/pi/MusicBot/LucasB25/PanaisSupport/events/interactionCreate.js:1654:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```
![image](https://github.com/ralphkb/sentinel-tickets/assets/50886682/9fc53a48-f2fc-4227-9f53-ac9fea920cf6)

**Comment by ralphkb** [comment]
Hey, please make sure to check each category in case you missed one where it's not an Array. Also please don't rename configuration options, the option is called `closedCategoryID` and not `closedcategoryID`, changing the name of the options might also be causing the issue.

The example in the latest config.yml.example looks like this:
```YAML
    categoryID: ["111111111111111111"] # The IDs of the categories where those tickets will be created, for example ["000000000000000000", "111111111111111111"]
    closedCategoryID: ["111111111111111111"] # The IDs of the categories where the closed tickets will go, for example ["000000000000000000", "111111111111111111"]
```
